"""Initial migration

Revision ID: 301d1dd93660
Revises: 
Create Date: 2025-10-20 01:57:16.228651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301d1dd93660'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pairs_id'), 'pairs', ['id'], unique=False)
    op.create_index(op.f('ix_pairs_symbol'), 'pairs', ['symbol'], unique=True)
    op.create_table('drawings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('drawing_metadata', sa.JSON(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['pairs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_pair_id'), 'drawings', ['pair_id'], unique=False)
    op.create_table('series',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('drawing_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drawing_id'], ['drawings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_drawing_id'), 'series', ['drawing_id'], unique=False)
    op.create_table('points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_points_id'), 'points', ['id'], unique=False)
    op.create_index(op.f('ix_points_series_id'), 'points', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_points_series_id'), table_name='points')
    op.drop_index(op.f('ix_points_id'), table_name='points')
    op.drop_table('points')
    op.drop_index(op.f('ix_series_drawing_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_drawings_pair_id'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_pairs_symbol'), table_name='pairs')
    op.drop_index(op.f('ix_pairs_id'), table_name='pairs')
    op.drop_table('pairs')
    # ### end Alembic commands ###
